### PR TITLE
Build fixes: certicoq and metacoq build scripts in coq 8.17.1

### PR DESCRIPTION
**Pull request by andrew-appel**

### CODE REVIEW

**Comment by andrew-appel** [comment]
@yforster can we discuss how to fix this?   I think the CI is failing because of opam configuration problems related to the metacoq submodule.

**Comment by yforster** [comment]
Yes, seems like it. I can't see the issue on my phone, but I'll give it ago tomorrow morning on my laptop, i think that should be quick

**Comment by andrew-appel** [comment]
This version builds on my own machine, so maybe it's some issue of my own submodule-version doesn't match what's committed.  But I wouldn't think so, given what "git status" and "git diff" say.

**Comment by yforster** [comment]
We need to adapt the CI script to the change in the opam file

**Comment by yforster** [comment]
CI works now, but it takes > 1 hour, which is a bit long. I'm experimenting with a new docker image to bring it down, see the open PR

**Comment by yforster** [comment]
The new image (with MetaCoq pre-installed) brings CI time down to about 30 minutes, that's a lot better. This PR can be merged!

**Pull request merged**
