### PR TITLE
Direct extraction from lambda box to L2k

### PR DESCRIPTION
**Pull request by yforster**
Using a new (not yet, but potentially certifying) eta expansion pass similar to ConCert and a verified parameter stripping pass on lambda box by @mattam82 we can go directly from lambda box to L2k.

MetaCoq's erasure is a lot faster now as well due to use of AVL trees for environments everywhere.

No proofs are done yet.

### CODE REVIEW

**Comment by andrew-appel** [comment]
AVL trees or Extensional Binary Tries, a.k.a. Canonical PTrees?  I thought I saw a message about that recently.

**Comment by yforster** [comment]
For now really AVL trees, but the definition is modular and in order to switch to Canonical PTrees we are just missing some injectivity proofs for a function sending kernames to positives.

**Comment by yforster** [comment]
We should even be able to compile the whole CertiCoq pipeline now :crossed_fingers:

**Comment by mattam82** [comment]
The good news is that we can indeed compile erasure, or even the whole certicoq pipeline, The bad news is that there is a bug, on this example:

MetaCoq Quote Recursively Definition foo := (true, false).
Definition metacoq_erasure := (erase_and_print_template_program foo).
CertiCoq Compile -O 0 -debug metacoq_erasure.

The compiled program should print:
```
 "pair true false
in:
Inductive prod(0 parameters,computational, elimination into any sort) := 
| pair 2 arguments
Inductive bool(0 parameters,computational, elimination into any sort) := 
| true 0 arguments
| false 0 arguments"
```
     
But I weirdly get: 
```
∎
in:
```

(I wrote a little wrapping code that decodes strings in C from the output and that has been tested a bit).

**Comment by mattam82** [comment]
The little black box above means that the C version erased this pair, for reasons I can't imagine.

**Comment by mattam82** [comment]
I found the first culprit: we didn't support `tProj` which do appear in the erasure function, they are now translated away.
Erasure goes further, but I'm still getting segmentation faults while running it.
I'm also getting this error when compiling `(List.map (fun x => negb x) [true])` (use this for the definition of `foo` in `benchmarks/metacoq_erasure.v`):

```
coqc -Q . CertiCoq.Benchmarks ErasureFunction.v &&
coqc -Q . CertiCoq.Benchmarks metacoq_erasure.v && gcc -I . -o metacoq_erasure -Wno-everything -O2 -fomit-frame-pointer metacoq_erasure_main.c gc.c CertiCoq.Benchmarks.metacoq_erasure.metacoq_erasure.c glue.CertiCoq.Benchmarks.metacoq_erasure.metacoq_erasure.c print.c && ./metacoq_erasure
Debug: Printed to file in 0.959332 s..
Nursery is too small for function's num_allocs
```
@intoverflow this is the gc bailing it seems, would you have an idea why? We are building big strings here, that might be the problem?

**Comment by mattam82** [comment]
The problem seems to be that I was linking with `gc.c` and not `gc_stack.c`, everything is fine with the later implementation.

**Comment by mattam82** [comment]
I don’t know how to launch the CI on this, any idea?

**Pull request merged**
