### PR TITLE
Compatibility with latest MetaCoq version and opam file for master (Coq 8.13)

### PR DESCRIPTION
**Pull request by yforster**
Same as #35, just updated to `coq-8.13`.

### CODE REVIEW

**Comment by joom** [comment]
Is there a plan to use the `coq-8.13` branch of MetaCoq as well? (the new `tCase` constructor etc)

**Comment by mattam82** [comment]
@joom we now have a working metacoq with the new case, but we only plan to release it for 8.14, so I'll update this branch for that

**Comment by joom** [comment]
I think @intoverflow made some progress on that already, but it's not finished as far as I know

**Comment by intoverflow** [comment]
I have slowly been working on bringing certicoq/master up to 8.13 with the latest Metacoq, but I haven't been able to give it the attention it deserves.

Link: https://github.com/intoverflow/certicoq/tree/tcarstens/coq-8.13

**Comment by mattam82** [comment]
Ok, I've a branch with tim's fixes now. But I'm getting errors in the compcert/flocq folder. Do you know how to get the right compcert there?

**Comment by mattam82** [comment]
@joom I'm a bit worried about the Prototype.v stuff: it seems to be moving from de Bruijn to a named representation somehow? Is that right? It should work still with the new cases by putting the right name annotations in the contexts of branches and predicates, but could you give me a gist of what the functions are doing? Are you pretty printing the produced Asts in some special way at the end?

**Comment by joom** [comment]
Sure. `named_of` takes a `term` in De Bruijn representation (containing `tRel`s) to a `term` in named representation, by generating fresh names for variables and then changing all `tRel`s to `tVar`s.

`indices_of` does the opposite. The "named representation"  is just for easily constructing `term`s, it has to be converted back to De Bruijn before passing to any primitives in the `TemplateMonad`.

I have essentially the same thing in the VeriFFI repo: https://github.com/CertiCoq/VeriFFI/blob/7d15951d7ca8bf24730de4620349211fcce39b28/generator/rep.v#L73-L253

I don't know about the rest. @john-ml would know the best. (rhyme unintended)

**Comment by mattam82** [comment]
Superseded by the latest update to MetaCoq and Coq 8.14

**Pull request closed without merging**
